[project]
name = "docly"
version = "0.1.0"
dependencies = [
    "click",
    "pathspec>=1.0.3",
    "pyyaml",
]

[project.scripts]
docly = "docly.pipelines.supervisor:cli"

[tool.setuptools]
packages = ["docly"]

[tool.setuptools.package-data]
"docly" = ["resources/*.gitignore"]
